//go:build ignore
// +build ignore

/*
	Note: This file is autogenerated! Do not edit it manually!
	Edit client_resource_template.go instead, and run
	hack/generate-client.sh afterwards.
*/

package client

import (
	"errors"
	"fmt"
	api "github.com/save-abandoned-projects/ignite/pkg/apis/ignite"
	"github.com/save-abandoned-projects/libgitops/pkg/filter"
	"github.com/save-abandoned-projects/libgitops/pkg/runtime"
	"github.com/save-abandoned-projects/libgitops/pkg/storage"
	log "github.com/sirupsen/logrus"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/apimachinery/pkg/types"
)

// ResourceClient is an interface for accessing Resource-specific API objects
type ResourceClient interface {
	// New returns a new Resource
	New() *api.Resource
	// Get returns the Resource matching given UID from the storage
	Get(types.UID) (*api.Resource, error)
	// Set saves the given Resource into persistent storage
	Set(*api.Resource) error
	// Patch performs a strategic merge patch on the object with
	// the given UID, using the byte-encoded patch given
	Patch(types.UID, []byte) error
	// Find returns the Resource matching the given filter, filters can
	// match e.g. the Object's Name, UID or a specific property
	Find(opt filter.ObjectFilter) (*api.Resource, error)
	// FindAll returns multiple Resources matching the given filter, filters can
	// match e.g. the Object's Name, UID or a specific property
	FindAll(opts filter.ListOptions) ([]*api.Resource, error)
	// Delete deletes the Resource with the given UID from the storage
	Delete(uid types.UID) error
	// List returns a list of all Resources available
	List() ([]*api.Resource, error)
}

// Resources returns the ResourceClient for the IgniteInternalClient instance
func (c *IgniteInternalClient) Resources() ResourceClient {
	if c.resourceClient == nil {
		c.resourceClient = newResourceClient(c.storage, c.gv)
	}

	return c.resourceClient
}

// resourceClient is a struct implementing the ResourceClient interface
// It uses a shared storage instance passed from the Client together with its own Filterer
type resourceClient struct {
	storage storage.Storage
	gvk     schema.GroupVersionKind
}

// newResourceClient builds the resourceClient struct using the storage implementation and a new Filterer
func newResourceClient(s storage.Storage, gv schema.GroupVersion) ResourceClient {
	return &resourceClient{
		storage: s,
		gvk:     gv.WithKind(api.KindResource.Title()),
	}
}

// New returns a new Object of its kind
func (c *resourceClient) New() *api.Resource {
	log.Tracef("Client.New; GVK: %v", c.gvk)

	obj, err := c.storage.Serializer().Defaulter().NewDefaultedObject(c.gvk)
	if err != nil {
		panic(fmt.Sprintf("Client.New must not return an error: %v", err))
	}
	// Cast to runtime.Object, and make sure it works
	metaObj, ok := obj.(runtime.Object)
	if !ok {
		panic("can't convert to libgitops.runtime.Object")
	}
	// Set the desired gvk from the caller of this Object
	// In practice, this means, although we created an internal type,
	// from defaulting external TypeMeta information was set. Set the
	// desired gvk here so it's correctly handled in all code that gets
	// the gvk from the Object
	metaObj.GetObjectKind().SetGroupVersionKind(c.gvk)
	return obj.(*api.Resource)
}

// Find returns a single Resource based on the given Filter
func (c *resourceClient) Find(opt filter.ObjectFilter) (*api.Resource, error) {
	log.Tracef("Client.Find; GVK: %v", c.gvk)

	objects, err := c.FindAll(filter.ListOptions{Filters: []filter.ListFilter{filter.ObjectToListFilter(opt)}})
	if err != nil {
		return nil, err
	}

	if len(objects) == 0 {
		return nil, nil
	}

	if len(objects) != 1 {
		return nil, errors.New("ambiguous query: AllFilter used to match single Object")
	}

	return objects[0], nil
}

// FindAll returns multiple Resources based on the given Filter
func (c *resourceClient) FindAll(opts filter.ListOptions) ([]*api.Resource, error) {
	log.Tracef("Client.FindAll; GVK: %v", c.gvk)
	matches, err := c.storage.List(storage.NewKindKey(c.gvk), nil)
	if err != nil {
		return nil, err
	}

	for _, filter := range opts.Filters {
		matches, err = filter.Filter(matches...)
		if err != nil {
			return nil, err
		}
	}
	results := make([]*api.Resource, 0, len(matches))
	for _, item := range matches {
		results = append(results, item.(*api.Resource))
	}

	return results, nil
}

// Get returns the Resource matching given UID from the storage
func (c *resourceClient) Get(uid types.UID) (*api.Resource, error) {
	log.Tracef("Client.Get; UID: %q, GVK: %v", uid, c.gvk)
	object, err := c.storage.Get(storage.NewObjectKey(storage.NewKindKey(c.gvk), runtime.NewIdentifier(string(uid))))
	if err != nil {
		return nil, err
	}

	return object.(*api.Resource), nil
}

// Set saves the given Resource into the persistent storage
func (c *resourceClient) Set(resource *api.Resource) error {
	log.Tracef("Client.Set; UID: %q, GVK: %v", resource.GetUID(), c.gvk)

	return c.storage.Update(resource)
}

// Patch performs a strategic merge patch on the object with
// the given UID, using the byte-encoded patch given
func (c *resourceClient) Patch(uid types.UID, patch []byte) error {
	return c.storage.Patch(storage.NewObjectKey(storage.NewKindKey(c.gvk), runtime.NewIdentifier(string(uid))), patch)
}

// Delete deletes the Resource from the storage
func (c *resourceClient) Delete(uid types.UID) error {
	log.Tracef("Client.Delete; UID: %q, GVK: %v", uid, c.gvk)
	return c.storage.Delete(storage.NewObjectKey(storage.NewKindKey(c.gvk), runtime.NewIdentifier(string(uid))))
}

// List returns a list of all Resources available
func (c *resourceClient) List() ([]*api.Resource, error) {
	log.Tracef("Client.List; GVK: %v", c.gvk)
	list, err := c.storage.List(storage.NewKindKey(c.gvk))
	if err != nil {
		return nil, err
	}

	results := make([]*api.Resource, 0, len(list))
	for _, item := range list {
		results = append(results, item.(*api.Resource))
	}

	return results, nil
}
